name: Integration Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
          cache-suffix: integration-tests
      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.14"
      - run:
          uv run python -m pytest -c pytest-integration.ini tests/integration/
          -v
